package com.egglib.xpro.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.egglib.xpro.model.User;
import com.egglib.xpro.model.Goods;

import com.egglib.xpro.db.UserDao;
import com.egglib.xpro.db.GoodsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig goodsDaoConfig;

    private final UserDao userDao;
    private final GoodsDao goodsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        goodsDaoConfig = daoConfigMap.get(GoodsDao.class).clone();
        goodsDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        goodsDao = new GoodsDao(goodsDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Goods.class, goodsDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        goodsDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public GoodsDao getGoodsDao() {
        return goodsDao;
    }

}
